#AnvilLogin configuration.
#Last updated: 09/08/17.
#If there are any bugs/errors, do not leave a review. Report them using github or the forums provided.

#The password people will use to login to your server.
Password: 'admin'
#Whether the player should be kicked after 30 seconds of not entering the correct password.
Timeout: true
#The message that the player gets when they are kicked. 30 second timeout.
Kickmsg: '&7[&9AnvilLogin&7] &cYou have been kicked for not entering the password within 30 seconds.'
#The message that the player gets when they log in.
Loggedinmsg: '&7[&9AnvilLogin&7] &aYou logged in to the server!'
#When the player closes the Anvil inventory, they will be kicked. This message will be displayed.
ClosedInventorymsg: '&7[&9AnvilLogin&7] &cYou need to enter a password!'