# AnvilLogin configuration.
# If there are any bugs/errors, do not leave a review. Report them using gitlab or discord.
# See lang for languages.

# The password people will use to login to your server. Will not be used if you are using AuthMe.
Password: 'admin'
# Whether the player should be kicked after 30 seconds of not entering the correct password.
Timeout: true
# The time, in ticks, until a player is kicked
Time: 600
# Whether to enable registering via the anvil (AuthMe only)
register: false
# Whether to print debugs
debug: false
# Whether to skip premium players (FastLogin only)
fastlogin: true
# Whether to display login messages or not
login_messages: true