# AnvilLogin configuration.
# If there are any bugs/errors, do not leave a review. Report them using gitlab or discord.
# See lang for languages.

# The password people will use to login to your server. Will not be used if you are using AuthMe.
Password: 'admin'
# Whether the player should be kicked after 30 seconds of not entering the correct password.
Timeout: true
# The time, in ticks, until a player is kicked
Time: 600
# Whether to enable registering via the anvil (AuthMe only)
register: false
# Whether to print debugs
debug: false
# Whether to skip premium players (FastLogin only)
fastlogin: true
# Whether to display login messages or not
login_messages: true

# The item to display in the left anvil slot
# Left slot cannot use name as it is used for the anvil text
# See lang/en_gb to modify anvil text
left_slot:
  type: ANVIL
  model: 0
  lore: []

# The item to display in the right anvil slot
# Note that this needs to be combinable with the left item for the player to be able to input the password
# This is a vanilla limitation
right_slot:
  type: AIR
  name: ""
  model: 0
  lore: []

# If this is enabled, everyone must enter a password regardless of permissions
disable-op-bypass: true

# The default language to use, see https://www.convallyria.com/javadoc/languagy/com/convallyria/languagy/api/language/Language.html
default_language: BRITISH_ENGLISH