name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    - run: git update-index --chmod=+x ./gradlew
    - name: Build
      run: ./gradlew build --stacktrace
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Download
        path: "build/libs/"